_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "CoTNext101-350epoch/cotdet.pth"
  MASK_ON: False
  BACKBONE:
    NAME: "build_cotnext_fpn_backbone"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
    NORM: "SyncBN"  
  FPN:
    NORM: "SyncBN"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
#DATALOADER:
#  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 800)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1333
  FORMAT: "RGB"
TEST:
  PRECISE_BN:
    ENABLED: True
