_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "CoTNet50-350epoch/cotdet.pth"
  MASK_ON: True
  BACKBONE:
    NAME: "build_cotnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
  ROI_MASK_HEAD:
    NORM: "SyncBN"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
#DATALOADER:
#  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  FORMAT: "RGB"
TEST:
  PRECISE_BN:
    ENABLED: True
